# create new windows in either the current dir, or the home dir
bind h new-window -c "~/"
bind c new-window -c "#{pane_current_path}"

# set vi-mode
set-window-option -g mode-keys vi
# keybindings take from https://superuser.com/questions/395158/tmux-copy-mode-select-text-block
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle \; send -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
